/**
 * Shared chrome for the homestead's building panels. The farmstead used to
 * be one screen with tabs; now that it's five separate map tiles they need
 * to look like the same game, so the panel styling lives here rather than
 * being copy-pasted into each one.
 */
export const panel: Record<string, React.CSSProperties> = {
  wrap: {
    background: '#fdf6e3',
    borderRadius: 12,
    padding: 'clamp(14px, 4vw, 24px)',
    width: 'min(420px, calc(100vw - 20px))',
    maxHeight: 'calc(100vh - 20px)',
    overflowY: 'auto',
    boxShadow: '0 12px 40px rgba(0,0,0,0.35)',
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
  },
  header: { display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' },
  title: { margin: 0, color: '#3a2e1f', fontSize: 21 },
  coins: { fontSize: 15, fontWeight: 700, color: '#8a6b1f' },
  subhead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    fontSize: 12.5,
    color: '#6b5a44',
  },
  toastSlot: { height: 20, display: 'flex', justifyContent: 'center', alignItems: 'center' },
  toast: {
    background: '#3a2e1f',
    color: '#fdf6e3',
    fontSize: 12.5,
    padding: '2px 10px',
    borderRadius: 10,
  },
  empty: { margin: '6px 0', fontSize: 13, color: '#8a7a63', textAlign: 'center' },
  hint: { margin: '0 0 4px', fontSize: 12.5, color: '#6b5a44', textAlign: 'center' },
  sectionLabel: {
    marginTop: 6,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#8a7a63',
    fontWeight: 700,
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    background: '#f2e6c9',
    borderRadius: 9,
    padding: 8,
  },
  rowReady: { background: '#e6efd4' },
  rowAlert: { background: '#f6ddd9' },
  rowArt: { flexShrink: 0, width: 48, display: 'flex', justifyContent: 'center' },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: {
    fontSize: 13.5,
    fontWeight: 600,
    color: '#3a2e1f',
    display: 'flex',
    alignItems: 'center',
    gap: 5,
  },
  rowNote: { fontSize: 11.5, color: '#6b5a44', marginTop: 1 },
  rowActions: { display: 'flex', flexDirection: 'column', gap: 4, flexShrink: 0 },
  tagAlert: {
    fontSize: 9,
    background: '#d9534f',
    color: 'white',
    borderRadius: 4,
    padding: '1px 4px',
    fontWeight: 700,
  },
  tagWarn: {
    fontSize: 9,
    background: '#d9a441',
    color: 'white',
    borderRadius: 4,
    padding: '1px 4px',
    fontWeight: 700,
  },
  barTrack: { height: 6, background: '#e3d5b8', borderRadius: 3, overflow: 'hidden', marginTop: 4 },
  barTrackThin: { flex: 1, height: 4, background: '#e3d5b8', borderRadius: 2, overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 3, transition: 'width 0.25s ease' },
  contentRow: { display: 'flex', alignItems: 'center', gap: 5, marginTop: 3 },
  contentLabel: {
    fontSize: 9.5,
    color: '#8a7a63',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  breedRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: '#f2e6c9',
    borderRadius: 8,
    padding: '5px 8px',
  },
  breedLabel: { flex: 1, fontSize: 12.5, color: '#3a2e1f' },
  button: {
    padding: '9px 20px',
    fontSize: 14,
    borderRadius: 8,
    border: 'none',
    background: '#7cb342',
    color: 'white',
    cursor: 'pointer',
  },
  smallButton: {
    padding: '5px 9px',
    fontSize: 11.5,
    borderRadius: 6,
    border: 'none',
    background: '#7cb342',
    color: 'white',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  darkButton: {
    padding: '5px 10px',
    fontSize: 11.5,
    borderRadius: 6,
    border: 'none',
    background: '#3a2e1f',
    color: '#fdf6e3',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  exitButton: {
    display: 'block',
    margin: '10px auto 0',
    background: 'none',
    border: 'none',
    color: '#8a7a63',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: 13,
  },
}
